pull_requests:
  do_not_increment_build_number: true
shallow_clone: true

image: Visual Studio 2015

environment:
  matrix:
    - PYTHON: "C:\\Python266"
      PYTHON_VERSION: "2.6.6"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python39"
      PYTHON_VERSION: "3.9.x"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python310"
      PYTHON_VERSION: "3.10.x"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python311"
      PYTHON_VERSION: "3.11.x"
      PYTHON_ARCH: "64"

install:
  # pywinpty installation fails without prior rust installation on some Python versions
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe -yv --default-toolchain stable --default-host i686-pc-windows-msvc
  - "SET PATH=%APPDATA%\\Python;%APPDATA%\\Python\\Scripts;%PYTHON%;%PYTHON%\\Scripts;c:\\MinGW\\bin;%PATH%;C:\\Users\\appveyor\\.cargo\\bin"
  - "copy c:\\MinGW\\bin\\mingw32-make.exe c:\\MinGW\\bin\\make.exe"
  - python -m pip install --user --upgrade setuptools pip
  - python -m pip install .[tests]

build: false

test_script:
  - make test-all
