repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.2.3
    hooks:
    -   id: check-byte-order-marker
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-vcs-permalinks
    -   id: check-ast
    -   id: check-json
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: pretty-format-json
        args:
        - --autofix
    -   id: flake8
        args:
        - --ignore=W503,E501,E265,E402,F405,E305,E126
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
        args:
        - --in-place
        - --aggressive
        - --aggressive
        - --experimental
        - --ignore=W503,E501,E722,E402
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v1.4.1
    hooks:
    -   id: add-trailing-comma
