-   repo: git://github.com/pre-commit/pre-commit-hooks.git
    sha: e626cd57090d8df0be21e4df0f4e55cc3511d6ab
    hooks:
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: autopep8-wrapper
        args:
        - --in-place
        - --aggressive
        - --aggressive
        - --ignore=W503,E501
    -   id: flake8
        args:
        - --ignore=W503,E501,E265,E402,F405,E305
