-   repo: git://github.com/pre-commit/pre-commit-hooks.git
    sha: 63142f2d4ece8fd67cad3521c6e0c0f2bfef1c03
    hooks:
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: autopep8-wrapper
        args:
        - --in-place
        - --aggressive
        - --aggressive
        - --ignore=W503,E501
    -   id: flake8
        args:
        - --ignore=W503,E501,E265,E402,F405
