language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

matrix:
  include:
    - python: "2.6"
      script:
        - coconut --version
        - coconut --strict --print --code "__coconut__ |> print"
        - echo "__coconut__ |> print" | coconut --strict --print
        - coconut src/runner.coc file_build --strict --autopep8
        - coconut src/cocotest/__init__.coc file_build/cocotest --strict --autopep8
        - coconut src/cocotest/main.coc file_build/cocotest --strict --autopep8
        - coconut src/cocotest/util.coc file_build/cocotest --strict --autopep8
        - python -tt file_build/runner.py
        - coconut src folder_build --strict --print --autopep8
        - python -tt folder_build/runner.py

install:
  - pip install .
  - pip install autopep8
  - pip install ipython
  - git clone https://github.com/evhub/cocotest.git
  - cd cocotest

script:
  - coconut --version
  - coconut --strict --print --code "__coconut__ |> print"
  - echo "__coconut__ |> print" | coconut --strict --print
  - ipython --ext coconut -c "%coconut __coconut__ |> print"
  - coconut src/runner.coc file_build --strict --autopep8
  - coconut src/cocotest/__init__.coc file_build/cocotest --strict --autopep8
  - coconut src/cocotest/main.coc file_build/cocotest --strict --autopep8
  - coconut src/cocotest/util.coc file_build/cocotest --strict --autopep8
  - python -tt file_build/runner.py
  - coconut src folder_build --strict --print --autopep8
  - python -tt folder_build/runner.py

notifications:
  email: false

sudo: false
