language: python

sudo: false

notifications:
  email: false

python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install "pip==7.1.2"
  - pip install -r ./reqs/requirements-dev.txt
  - make

script:
  - make test
