language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install .
  - pip install autopep8

script:
  - git clone https://github.com/evhub/cocotest.git
  - cd cocotest
  - coconut src build --strict --autopep8
  - python build/main.py -tt

notifications:
  email: false
