language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install .
  - pip install autopep8
  - pip install ipython
  - git clone https://github.com/evhub/cocotest.git
  - cd cocotest

script:
  - coconut --version
  - coconut --strict --print --debug --code "__coconut__ |> print"
  - echo "__coconut__ |> print" | coconut --strict --print --debug
  - ipython --ext coconut -c "%coconut __coconut__ |> print"
  - coconut src/cocotest build/cocotest --strict --print --debug --autopep8
  - coconut src/runner.coc build --strict --print --debug --autopep8
  - python build/runner.py -tt -vv

notifications:
  email: false

sudo: false
