language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install .
  - pip install autopep8
  - git clone https://github.com/evhub/cocotest.git
  - cd cocotest

script:
  - coconut --version
  - coconut --strict --debug 2 --exec "print(__coconut__)"
  - coconut src/cocotest build/cocotest --strict --print --debug 2 --autopep8
  - coconut src/runner.coc build --strict --print --debug 2 --autopep8
  - python build/runner.py -tt -vv

notifications:
  email: false
