language: python
notifications:
  email: false
sudo: false
cache: pip
python:
- '2.6'
- '2.7'
- pypy
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy3
env: USE_CONDA=false
matrix:
  include:
    - python: '2.7'
      env: USE_CONDA=true
install:
# if USE_CONDA == true:
- if [[ $USE_CONDA == "true" ]]; then
  rm -rf coconut; fi
- if [[ $USE_CONDA == "true" ]]; then
  wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; fi
- if [[ $USE_CONDA == "true" ]]; then
  bash miniconda.sh -b -p $HOME/miniconda; fi
- if [[ $USE_CONDA == "true" ]]; then
  export PATH="$HOME/miniconda/bin:$PATH"; fi
- if [[ $USE_CONDA == "true" ]]; then
  conda config --set always_yes yes; fi
- if [[ $USE_CONDA == "true" ]]; then
  conda install "conda-build>=3.0.8"; fi
- if [[ $USE_CONDA == "true" ]]; then
  conda skeleton pypi coconut-develop; fi
- if [[ $USE_CONDA == "true" ]]; then
  conda build coconut-develop; fi
- if [[ $USE_CONDA == "true" ]]; then
  conda install --use-local coconut-develop; fi
# if USE_CONDA == false:
- if [[ $USE_CONDA == "false" ]]; then
  pip install "pip==7.1.2"; fi
- if [[ $USE_CONDA == "false" ]]; then
  make install; fi
script:
- make test-all
deploy:
  provider: pypi
  user: evhub-develop
  password:
    secure: f5zfnO9cuMJyszSVG7h6ZZ0NtrQpI33NuCvyOEYeoLCL5815ANElRuBlGcP6KbydHM1rSp2/i62DXANy73U2mcPiQyiWUkhffOLxYnSGIMQ2hyRz2ZAopCusf5ZQFWH40NhT2q/gOnN/Cwyjd6KyU1oXSpolfROaE5aimu5dQcg=
  on:
    distributions: sdist bdist_wheel
    repo: evhub/coconut
    branch: develop
    condition: $USE_CONDA == "false"
