language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install pyparsing
  - pip install autopep8
  - pip install .

script:
  - git clone https://github.com/evhub/cocotest.git
  - cd cocotest
  - ./runtests.sh

notifications:
  email: false
