language: python

sudo: false

notifications:
  email: false

python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"

install:
  - pip install -r ./reqs/requirements-tests.txt
  - make

script:
  - make test
