language: python

sudo: false

notifications:
  email: false

matrix:
  include:

    - python: "2.6"

      install:
        - pip install .
        - pip install autopep8
        - git clone https://github.com/evhub/cocotest.git
        - cd cocotest
        - git clone https://github.com/evhub/prisoner.git
        - rm src/cocotest/py3_test.coc

      script:
        - coconut --version
        - coconut --strict --print --code "assert '__coconut__' in \`globals\`; msg = '<success>'; pmsg = print\$(msg); pmsg()"
        - echo "assert '__coconut__' in \`globals\`; msg = '<success>'; pmsg = print\$(msg); pmsg()" | coconut --strict --print
        - python -c "from coconut.convenience import parse; exec parse('assert \'__coconut__\' in \`globals\`; msg = \'<success>\'; pmsg = print\$(msg); pmsg()')"
        - coconut prisoner --strict

        - coconut src/runner.coc file_build --strict
        - coconut src/cocotest/__init__.coc file_build/cocotest --strict
        - coconut src/cocotest/main.coc file_build/cocotest --strict
        - coconut src/cocotest/util.coc file_build/cocotest --strict
        - coconut src/cocotest/py2_test.coc file_build/cocotest --strict --target 2
        - python -tt file_build/runner.py

        - coconut src/cocotest run_build/cocotest --strict
        - cp src/runner.coc run_build/runner.coc
        - cd run_build
        - coconut --run runner.coc --nowrite --strict
        - cd ..

        - coconut src folder_build --strict
        - python -tt folder_build/runner.py

        - coconut src autopep8_build --strict --autopep8
        - python -tt autopep8_build/runner.py

        - coconut src target_build --strict --print --target 2
        - python -tt target_build/runner.py

    - python: "2.7"

      install:
        - pip install .
        - pip install autopep8
        - pip install ipython
        - git clone https://github.com/evhub/cocotest.git
        - cd cocotest
        - git clone https://github.com/evhub/prisoner.git
        - rm src/cocotest/py3_test.coc

      script:
        - coconut --version
        - coconut --strict --print --code "assert '__coconut__' in \`globals\`; msg = '<success>'; pmsg = print\$(msg); pmsg()"
        - echo "assert '__coconut__' in \`globals\`; msg = '<success>'; pmsg = print\$(msg); pmsg()" | coconut --strict --print
        - python -c "from coconut.convenience import parse; exec parse('assert \'__coconut__\' in \`globals\`; msg = \'<success>\'; pmsg = print\$(msg); pmsg()')"
        - ipython --ext coconut -c "%coconut assert '__coconut__' in \`globals\`; msg = '<success>'; pmsg = print\$(msg); pmsg()"
        - coconut prisoner --strict

        - coconut src/runner.coc file_build --strict
        - coconut src/cocotest/__init__.coc file_build/cocotest --strict
        - coconut src/cocotest/main.coc file_build/cocotest --strict
        - coconut src/cocotest/util.coc file_build/cocotest --strict
        - coconut src/cocotest/py2_test.coc file_build/cocotest --strict --target 2
        - python -tt file_build/runner.py

        - coconut src/cocotest run_build/cocotest --strict
        - cp src/runner.coc run_build/runner.coc
        - cd run_build
        - coconut --run runner.coc --nowrite --strict
        - cd ..

        - coconut src folder_build --strict
        - python -tt folder_build/runner.py

        - coconut src autopep8_build --strict --autopep8
        - python -tt autopep8_build/runner.py

        - coconut src target_build --strict --print --target 2
        - python -tt target_build/runner.py

    - python: "3.3"

      install:
        - pip install .
        - pip install autopep8
        - pip install ipython
        - git clone https://github.com/evhub/cocotest.git
        - cd cocotest
        - git clone https://github.com/evhub/prisoner.git
        - rm src/cocotest/py2_test.coc

      script:
        - coconut --version
        - coconut --strict --print --code "assert '__coconut__' in \`globals\`; msg = '<success>'; pmsg = print\$(msg); pmsg()"
        - echo "assert '__coconut__' in \`globals\`; msg = '<success>'; pmsg = print\$(msg); pmsg()" | coconut --strict --print
        - python -c "from coconut.convenience import parse; exec(parse('assert \'__coconut__\' in \`globals\`; msg = \'<success>\'; pmsg = print\$(msg); pmsg()'))"
        - ipython --ext coconut -c "%coconut assert '__coconut__' in \`globals\`; msg = '<success>'; pmsg = print\$(msg); pmsg()"
        - coconut prisoner --strict

        - coconut src/runner.coc file_build --strict
        - coconut src/cocotest/__init__.coc file_build/cocotest --strict
        - coconut src/cocotest/main.coc file_build/cocotest --strict
        - coconut src/cocotest/util.coc file_build/cocotest --strict
        - coconut src/cocotest/py3_test.coc file_build/cocotest --strict --target 3
        - python -tt file_build/runner.py

        - coconut src/cocotest run_build/cocotest --strict
        - cp src/runner.coc run_build/runner.coc
        - cd run_build
        - coconut --run runner.coc --nowrite --strict
        - cd ..

        - coconut src folder_build --strict
        - python -tt folder_build/runner.py

        - coconut src autopep8_build --strict --autopep8
        - python -tt autopep8_build/runner.py

        - coconut src target_build --strict --print --target 3
        - python -tt target_build/runner.py

    - python: "3.4"

      install:
        - pip install .
        - pip install autopep8
        - pip install ipython
        - git clone https://github.com/evhub/cocotest.git
        - cd cocotest
        - git clone https://github.com/evhub/prisoner.git
        - rm src/cocotest/py2_test.coc

      script:
        - coconut --version
        - coconut --strict --print --code "assert '__coconut__' in \`globals\`; msg = '<success>'; pmsg = print\$(msg); pmsg()"
        - echo "assert '__coconut__' in \`globals\`; msg = '<success>'; pmsg = print\$(msg); pmsg()" | coconut --strict --print
        - python -c "from coconut.convenience import parse; exec(parse('assert \'__coconut__\' in \`globals\`; msg = \'<success>\'; pmsg = print\$(msg); pmsg()'))"
        - ipython --ext coconut -c "%coconut assert '__coconut__' in \`globals\`; msg = '<success>'; pmsg = print\$(msg); pmsg()"
        - coconut prisoner --strict

        - coconut src/runner.coc file_build --strict
        - coconut src/cocotest/__init__.coc file_build/cocotest --strict
        - coconut src/cocotest/main.coc file_build/cocotest --strict
        - coconut src/cocotest/util.coc file_build/cocotest --strict
        - coconut src/cocotest/py3_test.coc file_build/cocotest --strict --target 3
        - python -tt file_build/runner.py

        - coconut src/cocotest run_build/cocotest --strict
        - cp src/runner.coc run_build/runner.coc
        - cd run_build
        - coconut --run runner.coc --nowrite --strict
        - cd ..

        - coconut src folder_build --strict
        - python -tt folder_build/runner.py

        - coconut src autopep8_build --strict --autopep8
        - python -tt autopep8_build/runner.py

        - coconut src target_build --strict --print --target 3
        - python -tt target_build/runner.py
